-- Active: 1743266724610@@127.0.0.1@5433@caredb@admin_controll
CREATE TABLE "cursos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "descricao" text,
  "carga_horaria" int,
  "nivel" varchar,
  "categoria" varchar
);
CREATE TABLE "modulos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curso_id" int,
  "nome" varchar,
  "descricao" text,
  "carga_horaria" int,
  "ordem" int
);
CREATE TABLE "aulas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "modulo_id" int,
  "titulo" varchar,
  "descricao" text,
  "duracao" int
);
CREATE TABLE "alunos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "email" varchar,
  "telefone" varchar,
  "nascimento" date,
  "endereco" text
);
CREATE TABLE "instrutores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "especialidade" varchar,
  "biografia" text
);
CREATE TABLE "matriculas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "aluno_id" int,
  "curso_id" int,
  "data_matricula" date,
  "status" varchar
);
CREATE TABLE "aulas_completadas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "aluno_id" int,
  "aula_id" int,
  "data_conclusao" DATE
);
CREATE TABLE "cursos_instrutores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curso_id" int,
  "instrutor_id" int
);
ALTER TABLE "modulos" ADD FOREIGN KEY ("curso_id") REFERENCES "cursos" ("id");
ALTER TABLE "aulas" ADD FOREIGN KEY ("modulo_id") REFERENCES "modulos" ("id");
ALTER TABLE "matriculas" ADD FOREIGN KEY ("aluno_id") REFERENCES "alunos" ("id");
ALTER TABLE "matriculas" ADD FOREIGN KEY ("curso_id") REFERENCES "cursos" ("id");
ALTER TABLE "aulas_completadas" ADD FOREIGN KEY ("aluno_id") REFERENCES "alunos" ("id");
ALTER TABLE "aulas_completadas" ADD FOREIGN KEY ("aula_id") REFERENCES "aulas" ("id");
ALTER TABLE "cursos_instrutores" ADD FOREIGN KEY ("curso_id") REFERENCES "cursos" ("id");
ALTER TABLE "cursos_instrutores" ADD FOREIGN KEY ("instrutor_id") REFERENCES "instrutores" ("id");






















ALTER TABLE "alunos" ADD CONSTRAINT unique_email UNIQUE ("email");
CREATE INDEX idx_alunos_nascimento ON "alunos" ("nascimento");
CREATE INDEX idx_matriculas_data ON "matriculas" ("data_matricula");
ALTER TABLE "matriculas" ADD CONSTRAINT unique_aluno_curso UNIQUE ("aluno_id", "curso_id");
ALTER TABLE "cursos_instrutores" ADD CONSTRAINT unique_curso_instrutor UNIQUE ("curso_id", "instrutor_id");
ALTER TABLE "aulas_completadas" ADD CONSTRAINT unique_aluno_aula UNIQUE ("aluno_id", "aula_id");
ALTER TABLE "modulos" ADD CONSTRAINT unique_ordem_modulo_por_curso UNIQUE ("curso_id", "ordem");
ALTER TABLE "aulas" ADD CONSTRAINT unique_titulo_por_modulo UNIQUE ("modulo_id", "titulo");
CREATE INDEX idx_matriculas_aluno ON "matriculas" ("aluno_id");
CREATE INDEX idx_matriculas_curso ON "matriculas" ("curso_id");
CREATE INDEX idx_modulos_curso ON "modulos" ("curso_id");
CREATE INDEX idx_aulas_modulo ON "aulas" ("modulo_id");
CREATE INDEX idx_aulas_completadas_aluno ON "aulas_completadas" ("aluno_id");
CREATE INDEX idx_aulas_completadas_aula ON "aulas_completadas" ("aula_id");
CREATE INDEX idx_cursos_instrutores_instrutor ON "cursos_instrutores" ("instrutor_id");





























ALTER TABLE "cursos" ALTER COLUMN "nome" TYPE varchar(255);
ALTER TABLE "alunos" ALTER COLUMN "telefone" SET NOT NULL;












-- Populando a tabela de cursos
INSERT INTO "cursos" ("nome", "descricao", "carga_horaria", "nivel", "categoria") VALUES
('Curso de Python Básico', 'Curso introdutório sobre programação em Python', 40, 'Básico', 'Programação'),
('Curso de Desenvolvimento Web', 'Curso focado em desenvolvimento de aplicações web', 60, 'Intermediário', 'Desenvolvimento Web');

-- Populando a tabela de módulos
INSERT INTO "modulos" ("curso_id", "nome", "descricao", "carga_horaria", "ordem") VALUES
(1, 'Introdução ao Python', 'Introdução à linguagem Python', 10, 1),
(1, 'Estruturas de Dados', 'Estudo de listas, dicionários, conjuntos, etc.', 15, 2),
(1, 'Programação Orientada a Objetos', 'Conceitos de orientação a objetos', 15, 3),
(2, 'Fundamentos de HTML', 'Aprendendo HTML e suas tags', 10, 1),
(2, 'CSS Básico', 'Estilos e layouts com CSS', 15, 2),
(2, 'JavaScript e Interatividade', 'Adicionando interatividade com JavaScript', 20, 3);

-- Populando a tabela de aulas
INSERT INTO "aulas" ("modulo_id", "titulo", "descricao", "duracao") VALUES
(1, 'O que é Python?', 'Introdução à linguagem Python', 30),
(2, 'Listas e Dicionários', 'Como utilizar listas e dicionários em Python', 45),
(3, 'Classes e Objetos', 'Aprendendo sobre classes e objetos', 40),
(4, 'Estrutura de HTML', 'Aprenda a estrutura básica de uma página HTML', 40),
(5, 'CSS: Estilizando seu site', 'Introdução aos principais conceitos de CSS', 50),
(6, 'JavaScript Básico', 'Como escrever scripts para interatividade na página', 60);

-- Populando a tabela de alunos
INSERT INTO "alunos" ("nome", "email", "telefone", "nascimento", "endereco") VALUES
('Maria Silva', 'maria@example.com', '123456789', '1990-06-15', 'Rua A, 123, São Paulo'),
('João Santos', 'joao@example.com', '987654321', '1995-02-28', 'Rua B, 456, Rio de Janeiro'),
('Ana Oliveira', 'ana@example.com', '543216789', '2000-12-05', 'Rua C, 789, Belo Horizonte');

-- Populando a tabela de instrutores
INSERT INTO "instrutores" ("nome", "especialidade", "biografia") VALUES
('Carlos Souza', 'Python e Ciência de Dados', 'Instrutor com 10 anos de experiência em Python e análise de dados.'),
('Fernanda Costa', 'Desenvolvimento Web', 'Especialista em front-end, com mais de 5 anos de experiência em HTML, CSS e JavaScript.');

-- Populando a tabela de matrículas
INSERT INTO "matriculas" ("aluno_id", "curso_id", "data_matricula", "status") VALUES
(1, 1, '2025-04-01', 'Ativo'),
(2, 2, '2025-04-05', 'Ativo'),
(3, 1, '2025-04-07', 'Concluído');

-- Populando a tabela de aulas completadas
INSERT INTO "aulas_completadas" ("aluno_id", "aula_id", "data_conclusao") VALUES
(1, 1, '2025-04-10'),
(1, 2, '2025-04-11'),
(2, 4, '2025-04-12');

-- Populando a tabela de cursos_instrutores
INSERT INTO "cursos_instrutores" ("curso_id", "instrutor_id") VALUES
(1, 1),
(2, 2);


SELECT
  AVG(total_alunos_matriculados) AS media_alunos
FROM (
  SELECT
    EXTRACT(YEAR FROM data_matricula) AS ano,
    EXTRACT(MONTH FROM data_matricula) AS mes,
    COUNT(*) AS total_alunos_matriculados
  FROM
    matriculas
  GROUP BY
    EXTRACT(YEAR FROM data_matricula),
    EXTRACT(MONTH FROM data_matricula)
) AS sub;

SELECT
  data_conclusao,
  COUNT(*) AS total_alunos_presentes
FROM
  aulas_completadas
GROUP BY
  data_conclusao
ORDER BY
  COUNT(*);



SELECT 
    EXTRACT(YEAR FROM "nascimento") AS ano,
    EXTRACT(MONTH FROM "nascimento") AS mes,
    COUNT(*) AS quantidade_alunos
FROM "alunos"
GROUP BY ano, mes
ORDER BY ano, mes;

SELECT 
    "alunos"."nome", 
    COUNT("aulas_completadas"."id") AS quantidade_aulas_completas
FROM "aulas_completadas"
JOIN "alunos" ON "aulas_completadas"."aluno_id" = "alunos"."id"
GROUP BY "alunos"."id"
ORDER BY quantidade_aulas_completas DESC;
