// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP3.Data;

#nullable disable

namespace TP3.Migrations
{
    [DbContext(typeof(CityBreaksContext))]
    [Migration("20250914181633_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TP3.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("CityName");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "Nova Iorque"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 3,
                            Name = "Tóquio"
                        });
                });

            modelBuilder.Entity("TP3.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Country");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "BR",
                            CountryName = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "US",
                            CountryName = "Estados Unidos"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "JP",
                            CountryName = "Japão"
                        });
                });

            modelBuilder.Entity("TP3.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("PropertyName");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Hotel Copacabana",
                            PricePerNight = 750.00m
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Pousada Ipanema",
                            PricePerNight = 500.50m
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Name = "Apartamento na Paulista",
                            PricePerNight = 350.00m
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            Name = "Loft em Manhattan",
                            PricePerNight = 1200.00m
                        },
                        new
                        {
                            Id = 5,
                            CityId = 4,
                            Name = "Hotel com vista para o Monte Fuji",
                            PricePerNight = 1500.00m
                        });
                });

            modelBuilder.Entity("TP3.Models.City", b =>
                {
                    b.HasOne("TP3.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TP3.Models.Property", b =>
                {
                    b.HasOne("TP3.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TP3.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("TP3.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
