CREATE TABLE CHARACTERS (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255) NOT NULL,
                            status VARCHAR(100),
                            species VARCHAR(100),
                            type VARCHAR(100),
                            gender VARCHAR(50),
                            origin VARCHAR(255),
                            location VARCHAR(255),
                            image VARCHAR(500),
                            episode_count INTEGER
);

INSERT INTO characters (name, status, species, type, gender, origin, location, image, episode_count) VALUES ( 'Rick Sanchez', 'Alive', 'Human','', 'Male', 'Earth (C-137)', 'Citadel of Ricks', 'https://rickandmortyapi.com/api/character/avatar/1.jpeg', 51);
INSERT INTO characters (name, status, species, type, gender, origin, location, image, episode_count) VALUES ( 'Morty Smith', 'Alive', 'Human','', 'Male', 'unknown', 'Citadel of Ricks', 'https://rickandmortyapi.com/api/character/avatar/2.jpeg', 51);
INSERT INTO characters (name, status, species, type, gender, origin, location, image, episode_count) VALUES ( 'Summer Smith', 'Alive', 'Human','', 'Female', 'Earth (Replacement Dimension)', 'Earth (Replacement Dimension)', 'https://rickandmortyapi.com/api/character/avatar/3.jpeg', 42);
INSERT INTO characters (name, status, species, type, gender, origin, location, image, episode_count) VALUES ( 'Beth Smith', 'Alive', 'Human','', 'Female', 'Earth (Replacement Dimension)', 'Earth (Replacement Dimension)', 'https://rickandmortyapi.com/api/character/avatar/4.jpeg', 42);
INSERT INTO characters (name, status, species, type, gender, origin, location, image, episode_count) VALUES ( 'Jerry Smith', 'Alive', 'Human','', 'Male', 'Earth (Replacement Dimension)', 'Earth (Replacement Dimension)', 'https://rickandmortyapi.com/api/character/avatar/5.jpeg', 39);
INSERT INTO characters (name, status, species, type, gender, origin, location, image, episode_count) VALUES ( 'Abadango Cluster Princess', 'Alive', 'Alien','', 'Female', 'Abadango', 'Abadango', 'https://rickandmortyapi.com/api/character/avatar/6.jpeg', 1);
INSERT INTO characters (name, status, species, type, gender, origin, location, image, episode_count) VALUES ( 'Abradolf Lincler', 'unknown', 'Human', 'Genetic experiment', 'Male', 'Earth (Replacement Dimension)', 'Testicle Monster Dimension', 'https://rickandmortyapi.com/api/character/avatar/7.jpeg', 2);
INSERT INTO characters (name, status, species, type, gender, origin, location, image, episode_count) VALUES ( 'Adjudicator Rick', 'Dead', 'Human','', 'Male', 'unknown', 'Citadel of Ricks', 'https://rickandmortyapi.com/api/character/avatar/8.jpeg', 1);
INSERT INTO characters (name, status, species, type, gender, origin, location, image, episode_count) VALUES ( 'Agency Director', 'Dead', 'Human','', 'Male', 'Earth (Replacement Dimension)', 'Earth (Replacement Dimension)', 'https://rickandmortyapi.com/api/character/avatar/9.jpeg', 1);
INSERT INTO characters (name, status, species, type, gender, origin, location, image, episode_count) VALUES ( 'Alan Rails', 'Dead', 'Human', 'Superhuman (Ghost trains summoner)', 'Male', 'unknown', 'Worldenders lair', 'https://rickandmortyapi.com/api/character/avatar/10.jpeg', 1);
